# Site settings
title: revl.org
email: him@revl.org
description: > # this means to ignore newlines until "baseurl:"
  A blog about software development and other stuff that matters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://revl.org" # the base hostname & protocol for your site
github_username:  revl
permalink: /:slug/

# Build settings
markdown: kramdown
