# Site settings
title: revl.org
email: him@revl.org
description: > # this means to ignore newlines until "baseurl:"
  Damon Revoe's blog on software and related topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://revl.org" # the base hostname & protocol for your site
github_username:  revl
permalink: /:slug/

# Build settings
markdown: kramdown
